<?php
// Seta o título
$this->headTitle("Transação - Seleção");
?>

<form id="form_base" method="post" accept-charset="ISO-8859-1" onsubmit="return false;" action="">
    <fieldset>
        <legend>Transação</legend>
        
        <div class="linha">
            <div class="left">
                <label class="label_esquerda" for="cd_sistema">Nome do Sistema:</label>
                <?php echo $this->formSelect("cd_sistema", $this->form['cd_sistema'], array('class'=>'required'), $this->adicionaValorPadraoCombo($this->sistemas));?>
            </div>
            
            <div class="right">
                <label class="label_direita" for="cd_menu">Nome do Menu/Aba:</label>
                <?php echo $this->formSelect("cd_menu", $this->form['cd_menu'], array('class'=>'required'), $this->adicionaValorPadraoCombo($this->menus));?>
            </div>
        </div>
        
        <div class="linha">
            <div class="left">
                <label class="label_esquerda" for="cd_transacao">Código da Transação:</label>
                <?php echo $this->formText("cd_transacao", $this->form['cd_transacao'], array('class'=>'required', 'readonly'=>'readonly'));?>
            </div>
            
            <div class="right">
                <label class="label_direita" for="no_transacao">Nome da Transação:</label>
                <?php echo $this->formText("no_transacao", $this->form['no_transacao'], array('class'=>'required', 'maxlength'=>'60'));?>
            </div>
        </div>
        
        <div class="linha">
            <div class="left">
                <label class="label_esquerda" for="obj_executado">Objeto Executado:</label>
                <?php echo $this->formText("obj_executado", $this->form['obj_executado'], array('class'=>'required', 'maxlength'=>'200'));?>
            </div>
            
            <div class="right">
                <label class="label_direita" for="fl_tipo_transacao">Tipo de Transação:</label>
                <?php echo $this->formSelect("fl_tipo_transacao", $this->form['fl_tipo_transacao'], array(), $this->adicionaValorPadraoCombo(array("M"=>"Mestre", "D"=>"Detalhe")));?>
            </div>
        </div>
        
        <div class="linha">
            <div class="left">
                <label class="label_esquerda" for="amb_desenv">Ambiente de desenvolvimento:</label>
                <?php echo $this->formSelect("amb_desenv", $this->form['amb_desenv'], array('class'=>'required'), $this->adicionaValorPadraoCombo(array("POWR"=>"TEMPLATE POWER", "ZEND"=>"ZEND FRAMEWORK")));?>
            </div>
            
            <div class="right">
                <label class="label_direita" for="ord_transacao">Ordem de Exibição:</label>
                <?php echo $this->formText("ord_transacao", $this->form['ord_transacao'], array('maxlength'=>'2'));?>
            </div>
        </div>
        
        <div class="linha">
            <div class="left">
                <label class="label_esquerda" for="fl_visivel">Disponível para Acesso:</label>
                <?php echo $this->formSelect("fl_visivel", $this->form['fl_visivel'], array(), $this->adicionaValorPadraoCombo(array("1"=>"Sim", "0"=>"Não")));?>
            </div>
            
            <div class="right">
                <label class="label_direita" for="fl_publico">Acesso Público:</label>
                <?php echo $this->formSelect("fl_publico", $this->form['fl_publico'], array(), $this->adicionaValorPadraoCombo(array("1"=>"Sim", "0"=>"Não")));?>
            </div>
        </div>
        
        <div class="linha">
            <div class="left">
                <label class="label_esquerda" for="format_rel">Impressão da Listagem:</label>
                <?php echo $this->formSelect("format_rel", $this->form['format_rel'], array(), $this->adicionaValorPadraoCombo(array("P"=>"Paisagem", "R"=>"Retrato")));?>
            </div>
            
            <div class="right">
                <label class="label_direita" for="fl_nova_janela">Forma de Exibição:</label>
                <?php echo $this->formSelect("fl_nova_janela", $this->form['fl_nova_janela'], array(), $this->adicionaValorPadraoCombo(array("0"=>"Janela/Aba Principal", "1"=>"Nova Janela/Aba")));?>
            </div>
        </div>
        
        <div class="linha">
            <div class="left">
                <label class="label_esquerda" for="fl_log_sessao">Gera Log:</label>
                <?php echo $this->formSelect("fl_log_sessao", $this->form['fl_log_sessao'], array(), $this->adicionaValorPadraoCombo(array("1"=>"Sim", "0"=>"Não")));?>
            </div>
            
            <div class="right">
                <label class="label_direita" for="fl_relatorio">É Relatório:</label>
                <?php echo $this->formSelect("fl_relatorio", $this->form['fl_relatorio'], array(), $this->adicionaValorPadraoCombo(array("1"=>"Sim", "0"=>"Não")));?>
            </div>
        </div>

		<div class="linha">
			<div class="left">
                <label class="label_esquerda" for="no_arq_ajuda">Nome do Arquivo de Ajuda:</label>
                <?php echo $this->formText("no_arq_ajuda", $this->form['no_arq_ajuda'], array('maxlength'=>'200'));?>
            </div>
		</div>

        <div class="linha">
            <div class="full">
                <label class="label_esquerda" for="ds_transacao">Descrição da Transação:</label>
                <?php echo $this->formTextarea("ds_transacao", $this->form['ds_transacao'], array('maxlength'=>'300'));?>
            </div>
        </div>
                
    </fieldset>
    
</form>

<!-- Insere as Abas -->
<?php 
    // Define o código do contrato da transação pai
    $cd_transacao = "pai_cd_transacao/" . $this->form['cd_transacao'];

    // Define os atributos de cada aba
    $titulos        = array("Ações");
    $sistemas       = array("configuracoes-sistema");
    $controladores  = array("tab-transacao-acao");
    $parametros     = array($cd_transacao);
    $estilos        = array();
    
    // Gera as abas
    echo $this->geraAbas($titulos, $sistemas, $controladores, $parametros, $estilos);
?>