<?php
// Seta o título
$this->headTitle("Consulta - Listagem");
?>

<!-- Formulario de cadastro -->
<form id="form_pesquisar" method="post" accept-charset="ISO-8859-1" onsubmit="return false;" action="">
	
</form>


<table class='tabela' id='tabelaConsulta'>
<?php
// Se a consulta foi feita mostra os dados
if(count($this->paginator)) {
?>
    <thead>
      <tr>
		  <th class='cd_consulta'   column='mc.cd_consulta'>C&oacute;digo</th>
          <th class='titulo'        column='mc.titulo'>T&iacute;tulo</th>
          <th class='dthr_cadastro'	column='mc.dthr_cadastro'>Data Cadastro</th>
          <th class='cd_usuario'    column='mc.cd_usuario'>Usuário</th>
      </tr>
    </thead>
    <tfoot>
      <tr>
          <td colspan='4'><?php echo $this->paginationControl($this->paginator, 'Sliding', 'controle_paginacao.phtml', array('extraParams' => $this->extraParams)); ?></td>
      </tr>
    </tfoot>
    <tbody>
    <?php
    $i=0;
    foreach($this->paginator as $linha)
    {
        $key = "cd_consulta/{$linha->CD_CONSULTA}";
    ?>
        <tr class='linha' key='<?php echo $key; ?>'>
          <td><?php echo $linha->CD_CONSULTA; ?></td>
          <td><?php echo $linha->TITULO; ?></td>
          <td><?php echo $linha->DTHR_CADASTRO; ?></td>
          <td><?php echo $linha->CD_USUARIO; ?></td>
        </tr>
   <?php
        $i++;
    }
    ?>
	</tbody>
    <?php
} else {
   ?>
    <tfoot>
      <tr>
          <td colspan='4' class='paginacaoLinhaTabela' style='padding: 5px;'>Nenhum registo encontrado.</td>
      </tr>
    </tfoot>
<?php
}
?>
</table>
