<?php
// Seta o título
$this->headTitle("Grupos - Pesquisa");
?>

<table class='tabela' id='tabelaConsulta'>
<?php
// Se a consulta foi feita mostra os dados
if(count($this->paginator)) {
?>
    <thead>
      <tr>
          <th class='cd_grupo'      column='wg.cd_grupo'>Código<div class='img_seta'></div></th>
          <th class='no_grupo'      column='wg.no_grupo'>Nome do Grupo<div class='img_seta'></div></th>
          <th class='ds_grupo'      column='wg.ds_grupo'>Descrição do Grupo<div class='img_seta'></div></th>
          <th class='dt_acesso_ini' column='wgu.dt_acesso_ini' colspan='2'>Período de Acesso<div class='img_seta'></div></th>
      </tr>
    </thead>
    <tfoot>
      <tr>
          <td colspan='5'><?php echo $this->paginationControl($this->paginator, 'Sliding', 'controle_paginacao.phtml', array('extraParams' => $this->extraParams)); ?></td>
      </tr>
    </tfoot>
    <tbody>
    <?php
    $i=0;
    foreach($this->paginator as $linha)
    {
        $databaraporexclamacao = str_replace("/","!",$linha->DT_ACESSO_INI);
        
        $key = "cd_grupo/{$linha->CD_GRUPO}/dt_acesso_ini/{$databaraporexclamacao}";
       
    ?>
        <tr class='linha' key='<?php echo $key; ?>'>
          <td><?php echo $linha->CD_GRUPO; ?></td>
          <td><?php echo $linha->NO_GRUPO; ?></td>
          <td><?php echo $linha->DS_GRUPO; ?></td>
          <td class='dt_acesso_ini'><?php echo $linha->DT_ACESSO_INI; ?></td>
          <td class='dt_acesso_fim'><?php echo $linha->DT_ACESSO_FIM; ?></td>
        </tr>
   <?php
  
        $i++;
    }
    ?>
	</tbody>

    <?php
} else {
   ?>
    <tfoot>
      <tr>
          <td colspan='5' class='paginacaoLinhaTabela' style='padding: 5px;'>Nenhum registo encontrado.</td>
      </tr>
    </tfoot>
<?php
}
?>
</table>