<?php
// Seta o título
$this->headTitle("Grupo - Novo");
?>

<!-- Formulario de cadastro -->
<form id="form_base" method="post" accept-charset="ISO-8859-1" onsubmit="return false;" action="">
    <fieldset>
        <legend>Novo</legend>
        
        <?php echo $this->formHidden("cd_usuario", $this->pai_cd_usuario);?>
        
        <table class='tabela nao-selecionavel' id='tabelaCadastro'>                  
            <thead>
                <tr>
                    <th class='cd_grupo'>Código</th>
                    <th class='no_grupo'>Nome do Grupo</th>
                    <th class='ds_grupo'>Descrição do Grupo</th>
                    <th class='dt_acesso_ini' colspan='2'>Período de Acesso</th>
                </tr>
            </thead>
            <tbody>
                    <?php
                    // Captura a data atual
                    $dtAtual = date("d/m/Y");
                     
                    // Captura o valor da ordem de ação
                    $ultimaOrdemAcao = $this->ultimaOrdemAcao;
                    for($i = 0; $i < 10; $i++) {
                        // Joga no campo ord_acao os valores que 
                        // estão liberados para cadastro
                        if($i > 0) {
                            $ultimaOrdemAcao += 1;
                        }
                        
                        $classe = (($i%2)==0) ? "par" : "impar";
                    ?>  
                        <tr class='<?php echo $classe; ?>' indice='<?php echo $i; ?>'>
                          <td><?php echo $this->formText("cd_grupo[]",      null,     array('id'=>'cd_grupo_' . $i,      'class'=>'i_cd_grupo',      'title'=>'Código'));?></td>
                          <td><?php echo $this->formSelect("cd_grupo2[]",   null,     array('id'=>'cd_grupo2_' . $i,     'class'=>'i_no_grupo',      'title'=>'Nome do Grupo'), $this->adicionaValorPadraoCombo($this->grupos));?></td>
                          <td><?php echo $this->formText("ds_grupo[]",      null,     array('id'=>'ds_grupo_' . $i,      'class'=>'i_ds_grupo',      'title'=>'Descrição do Grupo', 'readonly'=>'readonly'));?></td>
                          <td style='width: 10%;'><?php echo $this->formText("dt_acesso_ini[]", $dtAtual, array('id'=>'dt_acesso_ini_' . $i, 'class'=>'i_dt_acesso_ini', 'maxlength'=>'10' , 'title'=>'Período inicial'));?></td>
                          <td style='width: 10%;'><?php echo $this->formText("dt_acesso_fim[]", null,     array('id'=>'dt_acesso_fim_' . $i, 'class'=>'i_dt_acesso_fim', 'maxlength'=>'10' , 'title'=>'Período final'));?></td>
                        </tr>
                    <?php
                    }
                ?>
            </tbody>
        </table>
        
    </fieldset>
    
</form>
