<?php
// Seta o título
$this->headTitle("Transação/Ação - Novo");
?>

<!-- Formulario de cadastro -->
<form id="form_base" method="post" accept-charset="ISO-8859-1" onsubmit="return false;" action="">
    <fieldset>
        <legend>Novo</legend>
        
        <?php echo $this->formHidden("cd_grupo", $this->pai_cd_grupo);?>
        
        <table class='tabela nao-selecionavel' id='tabelaCadastro'>                  
            <thead>
                <tr>
                    <th class='cd_usuario'>Username</th>
                    <th class='no_usuario'>Nome do Usuário</th>
                    <th class='tp_usuario'>Tipo de Usuário</th>
                    <th class='dt_acesso_ini' colspan='2'>Período de Acesso</th>
                </tr>
            </thead>
            <tbody>
                    <?php
                    // Captura a data atual
                    $dtAtual = date("d/m/Y");
                     
                    // Captura o valor da ordem de ação
                    $ultimaOrdemAcao = $this->ultimaOrdemAcao;
                    for($i = 0; $i < 10; $i++) {
                        // Joga no campo ord_acao os valores que 
                        // estão liberados para cadastro
                        if($i > 0) {
                            $ultimaOrdemAcao += 1;
                        }
                        
                        $classe = (($i%2)==0) ? "par" : "impar";
                    ?>  
                        <tr class='<?php echo $classe; ?>' indice='<?php echo $i; ?>'>
                          <td><?php echo $this->formSelect("cd_usuario[]",  null, array('id'=>'cd_usuario_' . $i, 'class'=>'i_cd_usuario', 'title'=>'Username'), $this->adicionaValorPadraoCombo($this->usernames));?></td>
                          <td><?php echo $this->formSelect("cd_usuario2[]", null, array('id'=>'cd_usuario2_' . $i, 'class'=>'i_no_usuario', 'title'=>'Nome do Usuário'), $this->adicionaValorPadraoCombo($this->usuarios));?></td>
                          <td><?php echo $this->formText("tp_usuario[]",    null, array('id'=>'tp_usuario_' . $i, 'class'=>'i_tp_usuario', 'title'=>'Tipo de Usuário', 'readonly'=>'readonly'));?></td>
                          <td><?php echo $this->formText("dt_acesso_ini[]", $dtAtual, array('id'=>'dt_acesso_ini_' . $i, 'class'=>'i_dt_acesso_ini', 'maxlength'=>'10' , 'title'=>'Período inicial'));?></td>
                          <td><?php echo $this->formText("dt_acesso_fim[]", null,     array('id'=>'dt_acesso_fim_' . $i, 'class'=>'i_dt_acesso_fim', 'maxlength'=>'10' , 'title'=>'Período final'));?></td>
                        </tr>
                    <?php
                    }
                ?>
            </tbody>
        </table>
        
    </fieldset>
    
</form>
