

	<br />

	<div id="img_login" style="border:0px solid #f00;">
		
	</div>

	<br />

	<form id="form_base" method="post" accept-charset="iso-8859-1" onsubmit="return false;" action="<?php echo $this->baseUrl();?>/login/">

		<fieldset style="border: 0px solid #fff; width: 400px !important; min-width: 400px !important;">
			
			<div class="linha">
				<div class="left" style="width:420;">
					<label style="width:147%;" class="label_esquerda" for="label1">Solicitação de nova senha realizada com sucesso.</label><br/><br/>
					<label style="width:200%;" class="label_esquerda" for="label2">Por favor entre em contato com o setor de informática da SUPRG pelo</label><br/>
					<label style="width:166%;" class="label_esquerda" for="label3">telefone (53) 3231-1366 Ramal 240, de Segunda à Sexta,</label><br/>
					<label style="width:120%;" class="label_esquerda" for="label4">das 07:30 às 11:30 e das 13:30 às 17:30.</label><br/><br/>
				</div>
			</div>
			
			<div class="linha" style="margin-top:10px;">
				<div class="left" style="width:400px;">
					<label style="width:35%;" class="label_esquerda">&nbsp;</label>
					<a style="width:200%;" id="principal" href="<?php echo $this->baseUrl();?>/login/">Acesso tela de Login</a>
				</div>
			</div>

		</fieldset>
	</form>
	

