<?php
// Seta o título
$this->headTitle("Tabelas - Pesquisa");
?>

<form name="f1">
	<input type="hidden" value="<?php echo $this->controleSalvar; ?>" name="controleSalvar" id="controleSalvar" />
    <?php
    // Seta as ligações entre as tabelas
    echo "<select id='coluna_tabelas_origem' style='display: none;'>";
    echo "<option value='_null_' label='-- Selecione --' sigla=''>-- Selecione --</option>";
    foreach($this->colTabelas as $colunaTabela) {
        $valor = trim($colunaTabela->SG_TABELA) . "." . $colunaTabela->CD_COLUNA;
        $label = trim($colunaTabela->SG_TABELA) . "." . $colunaTabela->NO_COLUNA;
        $sigla = trim($colunaTabela->SG_TABELA);
        echo "<option value='{$valor}' sigla='{$sigla}' coluna='{$colunaTabela->CD_COLUNA}' tp_coluna='{$colunaTabela->TP_COLUNA}' nome='{$colunaTabela->NO_COLUNA}' label='{$label}'>{$label}</option>";
    }
    echo "</select>";
    
    // Seta os totalizadores das colunas das tabelas
    echo "<select id='totais_origem' style='display: none;'>";
    echo "<option value='_null_' label='-- Selecione --' sigla=''>-- Selecione --</option>";
    foreach($this->totais as $total) {
        echo "<option value='{$total->CD_TP_TOTAL}' label='{$total->DS_TP_TOTAL}'>{$total->DS_TP_TOTAL}</option>";
    }
    echo "</select>";
    ?>
</form>

<form id="form_base" method="post" accept-charset="ISO-8859-1" onsubmit="return false;" action="">
    <input type="hidden" value="<?php echo $this->pai_cd_consulta; ?>" name="pai_cd_consulta" id="pai_cd_consulta" />
    <table class='tabela nao-ordenavel nao-selecionavel' id='tabelaConsulta'>
        <thead>
            <tr>
                <th class='distinto'>Distinto</th>
                <th class='coluna'>Coluna</th>
                <th class='cabecalho'>Cabeçalho</th>
                <!-- <th class='formato'>Formato</th> -->
                <th class='tamanho'>Tamanho %</th>
                <th class='total'>Totalizador</th>
                <th class='sentido'>Sentido Ordenação</th>
                <th class='add'><img class='add_col_tabela' alt='Nova Coluna' src='<?php echo $this->baseUrl(); ?>/public/images/botoes/16x16_adicionar.png' class='del_linha' /></th>
            </tr>
        </thead>
        <tbody>
        </tbody>
    </table>
</form>