<?php
// Seta o título
$this->headTitle("Grupo - Novo");
?>

<!-- Formulario de cadastro -->
<form id="form_base" method="post" accept-charset="ISO-8859-1" onsubmit="return false;" action="">
    <fieldset>
        <legend>Grupo</legend>

        <div class="linha">
            <div class="left">
                <label class="label_esquerda" for="cd_grupo">Código do Grupo:</label>
                <?php echo $this->formText("cd_grupo", "", array('readonly'=>'readonly', 'maxlength'=>'5'));?>
            </div>

            <div class="right">
                <label class="label_direita" for="no_grupo">Nome do Grupo:</label>
                <?php echo $this->formText("no_grupo", "", array('maxlength'=>'40'));?>
            </div>

            
        </div>

        <div class="linha">
            <div class="full">
                <label class="label_esquerda" for="ds_grupo">Descrição do Grupo:</label>
                <?php echo $this->formTextarea("ds_grupo", "", array('maxlength'=>'300'));?>
            </div>
            
            
        </div>
        
    </fieldset>
    
</form>
