<div id="cabecalho_botoes">

    <div>
        <a onclick="Interna.telapesquisa();" id="pesquisar">
            <div class="btn_pesq" style="background-image: url('<?=$this->baseUrl();?>/public/images/bt_consulta.jpg');" >&nbsp;</div>
            <div class="btn_pesq_meio" style="background-image: url('<?=$this->baseUrl();?>/public/images/bt_p2_over.jpg');" ><p class="tit_botao">Pesquisa / Manutenção</p></div>
            <div class="btn_pesq_ct" style="background-image: url('<?=$this->baseUrl();?>/public/images/bt_p3.jpg');" >&nbsp;</div>
        </a>
    </div>

    <div>
       <a onclick="Interna.novo();" id="novo">
            <div class="btn_pesq" style="background-image: url('<?=$this->baseUrl();?>/public/images/bt_manutencao.jpg');" >&nbsp;</div>
            <div class="btn_pesq_meio" style="background-image: url('<?=$this->baseUrl();?>/public/images/bt_p2_out.jpg');" ><p class="tit_botao">Novo registro</p></div>
            <div class="btn_pesq_ct" style="background-image: url('<?=$this->baseUrl();?>/public/images/bt_p3.jpg');" >&nbsp;</div>
        </a>
    </div>
    <a onclick="Interna.ajuda();" id="ajuda">
        <div>
            <div class="btn_pesq" style="background-image: url('<?=$this->baseUrl();?>/public/images/bt_ajuda.jpg');" >&nbsp;</div>
            <div class="btn_pesq_meio" style="background-image: url('<?=$this->baseUrl();?>/public/images/bt_p2_out.jpg');" ><p class="tit_botao">Ajuda</p></div>
            <div class="btn_pesq_ct" style="background-image: url('<?=$this->baseUrl();?>/public/images/bt_p3.jpg');" >&nbsp;</div>
        </div>
    </a>

</div>