<?php
// Seta o título
$this->headTitle("Grupo/Usuario - Pesquisa");
?>

<table class='tabela' id='tabelaConsulta'>
<?php
// Se a consulta foi feita mostra os dados
if(count($this->paginator)) {
?>
    <thead>
      <tr>
          <th class='cd_grupo' column='gp.cd_grupo'>Código do Grupo</th>
          <th class='no_grupo' column='gp.no_grupo'>Nome do Grupo</th>
      </tr>
    </thead>
    <tfoot>
      <tr>
          <td colspan='2'><?php echo $this->paginationControl($this->paginator, 'Sliding', 'controle_paginacao.phtml', array('extraParams' => $this->extraParams)); ?></td>
      </tr>
    </tfoot>
    <tbody>
    <?php
    $i=0;
    foreach($this->paginator as $linha)
    {
        $key = "cd_mensagem/{$linha->CD_MENSAGEM}/cd_grupo/{$linha->CD_GRUPO}";
    ?>
        <tr class='linha' key='<?php echo $key; ?>'>
          <td><?php echo $linha->CD_GRUPO; ?></td>
          <td><?php echo $linha->NO_GRUPO; ?></td>
        </tr>
   <?php
        $i++;
    }
    ?>
	</tbody>

    <?php
} else {
   ?>
    <tfoot>
      <tr>
          <td colspan='2' class='paginacaoLinhaTabela' style='padding: 5px;'>Nenhum registo encontrado.</td>
      </tr>
    </tfoot>
<?php
}
?>
</table>