<?php
// Seta o título
$this->headTitle("Clientes - Pesquisa");
?>

<table class='tabela' id='tabelaConsulta'>
<?php
// Se a consulta foi feita mostra os dados
if(count($this->paginator)) {
?>
    <thead>
      <tr>
          <th class='cd_cliente'   column='c.cd_cliente'>Código<div class='img_seta'></div></th>
          <th class='razao_social' column='c.razao_social'>Razão Social<div class='img_seta'></div></th>
          <th class='fl_principal' column='uc.fl_principal'>Principal<div class='img_seta'></div></th>
      </tr>
    </thead>
    <tfoot>
      <tr>
          <td colspan='3'><?php echo $this->paginationControl($this->paginator, 'Sliding', 'controle_paginacao.phtml', array('extraParams' => $this->extraParams)); ?></td>
      </tr>
    </tfoot>
    <tbody>
    <?php
    $i=0;
    foreach($this->paginator as $linha)
    {
        $key = "cd_cliente/{$linha->CD_CLIENTE}";
    ?>
        <tr class='linha' key='<?php echo $key; ?>'>
          <td><?php echo $linha->CD_CLIENTE; ?></td>
          <td><?php echo $linha->RAZAO_SOCIAL; ?></td>
          <td><?php echo ($linha->FL_PRINCIPAL == "" || $linha->FL_PRINCIPAL == 0 ? "Não" : "Sim"); ?></td>
        </tr>
   <?php
        $i++;
    }
    ?>
	</tbody>

    <?php
} else {
   ?>
    <tfoot>
      <tr>
          <td colspan='3' class='paginacaoLinhaTabela' style='padding: 5px;'>Nenhum registo encontrado.</td>
      </tr>
    </tfoot>
<?php
}
?>
</table>