<?php
// Seta o título
$this->headTitle("Clientes - Editar");
?>

<!-- Formulario de cadastro -->
<form id="form_base" method="post" accept-charset="ISO-8859-1" onsubmit="return false;" action="">
    <fieldset>
        <legend>Editar</legend>
        
        <?php echo $this->formHidden("cd_usuario", $this->form['cd_usuario']);?>
        
        <div class="linha">
            <div class="left">
                <label class="label_esquerda" for="cd_cliente">Código do Grupo:</label>
                <?php echo $this->formText("cd_cliente", $this->form['cd_cliente'], array('readonly'=>'readonly', 'maxlength'=>'6'));?>
            </div>
        </div>
        
        <div class="linha">
            <div class="left">
                <label class="label_esquerda" for="razao_social">Código do Grupo:</label>
                <?php echo $this->formText("razao_social", $this->form['razao_social'], array('readonly'=>'readonly', 'maxlength'=>'50'));?>
            </div>
            
            <div class="right">
                <label class="label_direita" for="fl_principal">Cliente Principal:</label>
                <?php echo $this->formSelect("fl_principal", ($this->form['fl_principal'] == "" || $this->form['fl_principal'] == 0 ? "0" : "1"), array('title'=>'Cliente Principal'), $this->adicionaValorPadraoCombo(array("1"=>"Sim", "0"=>"Não")));?>
            </div>
        </div>
        
    </fieldset>
    
</form>
