<?php
// Seta o título
$this->headTitle("Grupos - Novo");
?>

<!-- Formulario de cadastro -->
<form id="form_base" method="post" accept-charset="ISO-8859-1" onsubmit="return false;" action="">
    <fieldset>
        <legend>Novo Grupo</legend>
		<?php echo $this->formHidden("cd_consulta", $this->pai_cd_consulta);?>
        <table class='tabela nao-selecionavel'>
            <thead>
                <tr>
                    <th class='cd_grupo' style="width:10%">Código do Grupo</th>
                    <th class='no_grupo' style="width:40%">Nome do Grupo</th>
                    <th class='ds_grupo' style="width:50%">Descrição do Grupo</th>

                </tr>
            </thead>
            <tbody>
                    <?php 
                    for($i = 0; $i < 5; $i++) {
						//define a cor da linha
                        $classe = (($i%2)==0) ? "par" : "impar";
                    ?>  
                        <tr class='<?php echo $classe; ?>' indice='<?php echo $i; ?>'>
                          <td><?php echo $this->formText("cd_grupo[]", null, array('id'=>'cd_grupo'. $i, 'class'=>'int_e cdGrupo', 'title'=>'Cód Grupo', 'maxlength'=>'5', 'indice'=>$i));?></td>
                          <td><?php echo $this->formText("no_grupo[]", null, array('id'=>'no_grupo'. $i, 'class'=>'auto-complete-x stru noGrupo', 'maxlength'=>'50', 'indice'=>$i, 'style'=>'width:100%'));?></td>
                          <td><?php echo $this->formText("ds_grupo[]", null, array('id'=>'ds_grupo'. $i, 'class'=>'ds_grupo', 'title'=>'Descrição do Grupo', 'readonly'=>'readonly', 'style'=>'width:100%'));?></td>
                        </tr>
                    <?php
                    }
                ?>
            </tbody>
        </table>
        
    </fieldset>
    
</form>
