<?php
// Seta o título
$this->headTitle("Grupos - Listagem");
?>

<!-- Formulario de cadastro -->
<form id="form_pesquisar" method="post" accept-charset="ISO-8859-1" onsubmit="return false;" action=""></form>


<fieldset>
    <legend>Grupos com Permissão de Visualização do Relatório</legend>
    <table class='tabela' id='tabelaConsulta'>
    <?php
    // Se a consulta foi feita mostra os dados
    if(count($this->paginator)) {
    ?>
        <thead>
          <tr>
              <th class='cd_grupo' column='mc.cd_grupo'>C&oacute;digo</th>
              <th class='no_grupo' column='mc.no_grupo'>Nome</th>
              <th class='ds_grupo' column='mc.ds_grupo'>Descrição</th>
          </tr>
        </thead>
        <tfoot>
          <tr>
              <td colspan='3'><?php echo $this->paginationControl($this->paginator, 'Sliding', 'controle_paginacao.phtml', array('extraParams' => $this->extraParams)); ?></td>
          </tr>
        </tfoot>
        <tbody>
        <?php
        $i=0;
        foreach($this->paginator as $linha)
        {
            $key = "cd_grupo/{$linha->CD_GRUPO}";
        ?>
            <tr class='linha' key='<?php echo $key; ?>'>
              <td><?php echo $linha->CD_GRUPO; ?></td>
              <td><?php echo $linha->NO_GRUPO; ?></td>
              <td><?php echo $linha->DS_GRUPO; ?></td>
            </tr>
       <?php
            $i++;
        }
        ?>
        </tbody>
        <?php
    } else {
       ?>
        <tfoot>
          <tr>
              <td colspan='3' class='paginacaoLinhaTabela' style='padding: 5px;'>Nenhum registo encontrado.</td>
          </tr>
        </tfoot>
    <?php
    }
    ?>
    </table>
</fieldset>
