<?php
// Seta o título
$this->headTitle("Tabelas - Pesquisa");
?>

<form name="f1">
    <input type="hidden" value="<?php echo $this->atualizaTelaPrincipal; ?>" name="controleAtualiza" id="controleAtualiza" />
	<input type="hidden" value="<?php echo $this->controleSalvar; ?>" name="controleSalvar" id="controleSalvar" />
    <?php
    echo "<select id='tabelas_origem' style='display: none;'>";
    echo "<option value='_null_' label='-- Selecione --' sigla=''>-- Selecione --</option>";
    foreach($this->tabelas as $tabela) {
        echo "<option value='{$tabela->CD_TABELA}' sigla='{$tabela->SG_TABELA}' label='{$tabela->NO_TABELA}'>{$tabela->NO_TABELA}</option>";
    }
    echo "</select>";
    ?>
</form>

<form id="form_base" method="post" accept-charset="ISO-8859-1" onsubmit="return false;" action="">
    <input type="hidden" value="<?php echo $this->pai_cd_consulta; ?>" name="pai_cd_consulta" id="pai_cd_consulta" />
    <table class='tabela nao-ordenavel nao-selecionavel' id='tabelaConsulta'>
        <thead>
            <tr>
                <th class='no_tabela' column='tb.cd_tabela'>Nome da Tabela</th>
                <th class='sg_tabela' column='tb.no_tabela'>Silgla da Tabela</th>
                <th class='add'><img class='add_tabela' alt='Nova Tabela' src='<?php echo $this->baseUrl(); ?>/public/images/botoes/16x16_adicionar.png' class='del_linha' /></th>
            </tr>
        </thead>
        <tbody>
        </tbody>
    </table>
</form>
