<?php
// Seta o título
$this->headTitle("Colunas - Pesquisa");
?>

<table class='tabela' id='tabelaConsulta'>
<?php
// Se a consulta foi feita mostra os dados
if(count($this->paginator)) {
?>
    <thead>
      <tr>
          <th class='cd_coluna' column='cd_coluna'>Código<div class='img_seta'></div></th>
          <th class='no_coluna' column='no_coluna'>Nome<div class='img_seta'></div></th>
          <th class='fl_pk'     column='fl_pk'>Chave Primária<div class='img_seta'></div></th>                    
          <th class='tp_coluna' column='tp_coluna'>Tipo<div class='img_seta'></div></th>
          <th class='tamanho'   column='tamanho'>Tamanho<div class='img_seta'></div></th>          
      </tr>
    </thead>
    <tfoot>
      <tr>
          <td colspan='5'><?php echo $this->paginationControl($this->paginator, 'Sliding', 'controle_paginacao.phtml', array('extraParams' => $this->extraParams)); ?></td>
      </tr>
    </tfoot>
    <tbody>
    <?php
    $i=0;
    foreach($this->paginator as $linha)
    {
        $key = "cd_tabela/{$linha->CD_TABELA}/cd_coluna/{$linha->CD_COLUNA}";

    ?>
        <tr class='linha' key='<?php echo $key; ?>'>
          <td class='cd_coluna stru'> <?php echo $linha->CD_COLUNA;     ?></td>
          <td class='no_coluna strl'> <?php echo $linha->NO_COLUNA;     ?></td>          
          <td class='fl_pk stru'>     <?php echo $linha->getFlPk();     ?></td>          
          <td class='tp_coluna stru'> <?php echo $linha->getTpColuna(); ?></td>
          <td class='tamanho dec'>
          	<?php 
          		if($linha->getTpColuna() == "NUMBER") {
          			echo $this->formataValor($linha->TAMANHO);
          		} else {
          			echo $linha->TAMANHO;
          		}
          	?>
          </td>
        </tr>
   <?php
        $i++;
    }
    ?>
	</tbody>

    <?php
} else {
   ?>
    <tfoot>
      <tr>
          <td colspan='5' class='paginacaoLinhaTabela' style='padding: 5px;'>Nenhum registo encontrado.</td>
      </tr>
    </tfoot>
<?php
}
?>
</table>