<?php
// Seta o título
$this->headTitle("Transação/Ação - Pesquisa");
?>

<table class='tabela' id='tabelaConsulta'>
<?php
// Se a consulta foi feita mostra os dados
if(count($this->paginator)) {
?>
    <thead>
      <tr>
          <th class='cd_sistema' column='ws.cd_sistema'><?php echo $this->traducao["LB_COD_TRANSACAO"];?></th>
          <th class='cd_sistema' column='ws.cd_sistema'><?php echo $this->traducao["LB_NO_TRANSACAO"];?></th>
          <th class='cd_sistema' column='ws.cd_sistema'><?php echo $this->traducao["LB_CD_ACAO"];?></th>
          <th class='cd_sistema' column='ws.cd_sistema'><?php echo $this->traducao["LB_NO_ACAO"];?></th>
          <th class='cd_sistema' column='ws.cd_sistema'><?php echo $this->traducao["LB_ORDEM"];?></th>
      </tr>
    </thead>
    <tfoot>
      <tr>
          <td colspan='5'><?php echo $this->paginationControl($this->paginator, 'Sliding', 'controle_paginacao.phtml', array('extraParams' => $this->extraParams)); ?></td>
      </tr>
    </tfoot>
    <tbody>
    <?php
    $i=0;
    foreach($this->paginator as $linha)
    {
        $key = "cd_transacao/{$linha->CD_TRANSACAO}/cd_acao/{$linha->CD_ACAO}";

    ?>
        <tr class='linha' key='<?php echo $key; ?>'>
          <td><?php echo $linha->CD_TRANSACAO; ?></td>
          <td><?php echo $linha->NO_TRANSACAO; ?></td>
          <td><?php echo $linha->CD_ACAO; ?></td>
          <td><?php echo $linha->NO_ACAO; ?></td>
          <td><?php echo $linha->ORD_ACAO; ?></td>
        </tr>
   <?php
        $i++;
    }
    ?>
	</tbody>

    <?php
} else {
   ?>
    <tfoot>
      <tr>
          <td colspan='5' class='paginacaoLinhaTabela' style='padding: 5px;'>Nenhum registo encontrado.</td>
      </tr>
    </tfoot>
<?php
}
?>
</table>