<?php echo $this->doctype();
	// Captura os dados da requisição
	$no_module     = $this->no_module;
	$no_controller = $this->no_controller;
	$no_action     = $this->no_action;
    $cd_transacao  = $this->extraParams["_cd_transacao"];
    $jasperUrl     = JASPER_URL;
    $fl_tipo_transacao = $_SESSION["portoweb"][$no_module][$no_controller]["_fl_tipo_transacao"];
    $fl_permissao      = $_SESSION["portoweb"][$no_module][$no_controller]["_fl_permissao"];
	
	// Captura a sessão
	$sessao = new Zend_Session_Namespace('portoweb');
	
	// Escode o menu da direita para o layout velho
	$layoutVelho = "";
	if (isset($sessao->perfil->layoutVelho)) {
		$layoutVelho = "display:none;";	
	}
	
	// Captura o local de origem do servidor onde estão os arquivos
	$documentRoot = substr($_SERVER["DOCUMENT_ROOT"], 0, -1);
?>
<html>
<head>
	<?php echo $this->headTitle()."\n";?>
	<?php echo $this->headMeta()."\n";?>
	
	<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl();?>/public/styles/base.css" />
	<style type="text/css">
		<?php	
			// Lê os arquivos CSS
			Zend_Loader::loadFile($documentRoot . $this->baseUrl() . "/public/js/jquery/jquery-ui/development-bundle/themes/marca/jquery.ui.core.css"); echo "\n";
			Zend_Loader::loadFile($documentRoot . $this->baseUrl() . "/public/js/jquery/jquery-ui/development-bundle/themes/marca/jquery.ui.resizable.css"); echo "\n";
			Zend_Loader::loadFile($documentRoot . $this->baseUrl() . "/public/js/jquery/jquery-ui/development-bundle/themes/marca/jquery.ui.selectable.css"); echo "\n";
			Zend_Loader::loadFile($documentRoot . $this->baseUrl() . "/public/js/jquery/jquery-ui/development-bundle/themes/marca/jquery.ui.accordion.css"); echo "\n";
			Zend_Loader::loadFile($documentRoot . $this->baseUrl() . "/public/js/jquery/jquery-ui/development-bundle/themes/marca/jquery.ui.autocomplete.css"); echo "\n";
			Zend_Loader::loadFile($documentRoot . $this->baseUrl() . "/public/js/jquery/jquery-ui/development-bundle/themes/marca/jquery.ui.button.css"); echo "\n";
			Zend_Loader::loadFile($documentRoot . $this->baseUrl() . "/public/js/jquery/jquery-ui/development-bundle/themes/marca/jquery.ui.dialog.css"); echo "\n";
			Zend_Loader::loadFile($documentRoot . $this->baseUrl() . "/public/js/jquery/jquery-ui/development-bundle/themes/marca/jquery.ui.slider.css"); echo "\n";
			Zend_Loader::loadFile($documentRoot . $this->baseUrl() . "/public/js/jquery/jquery-ui/development-bundle/themes/marca/jquery.ui.tabs.css"); echo "\n";
			Zend_Loader::loadFile($documentRoot . $this->baseUrl() . "/public/js/jquery/jquery-ui/development-bundle/themes/marca/jquery.ui.datepicker.css"); echo "\n";
			Zend_Loader::loadFile($documentRoot . $this->baseUrl() . "/public/js/jquery/jquery-ui/development-bundle/themes/marca/jquery.ui.progressbar.css"); echo "\n";
			Zend_Loader::loadFile($documentRoot . $this->baseUrl() . "/public/styles/mascara.css"); echo "\n";
		?>
	</style>
    <?php 
	$documentRoot     = substr($_SERVER["DOCUMENT_ROOT"], 0, -1);
	$caminhoCssAction = "{$documentRoot}{$this->baseUrl()}/public/styles/{$no_action}.css";
	// Verifica se o arquivo existe
	if(is_file($caminhoCssAction)) {
	?>
	<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl();?>/public/styles/<?php echo $no_action;?>.css" />
    <?php
	} 
	?>
	<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl();?>/public/styles/<?php echo $no_module;?>/<?php echo $no_controller;?>.css" />
	<?php 
	$caminhoCssAction = "{$documentRoot}{$this->baseUrl()}/public/styles/{$no_module}/{$no_controller}-{$no_action}.css";
	// Verifica se o arquivo existe
	if(is_file($caminhoCssAction)) {
	?>
	<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl();?>/public/styles/<?php echo $no_module;?>/<?php echo $no_controller;?>-<?php echo $no_action;?>.css" />
	<?php
	} 
	?>
	<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl();?>/public/styles/imagens.css" />
	<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl();?>/public/js/jquery/jquery-ui/development-bundle/themes/marca/jquery.ui.all.css" />
	<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl();?>/public/js/jquery/plugins/jquery.loading.1.6.css" />
	<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl();?>/public/js/jquery/plugins/jquery-tooltip/jquery.tooltip.css" />
    <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl();?>/public/js/jquery/plugins/jquery.ui.datetime.css" />
    
	
	<?php echo $this->headLink(); ?>
	<?php echo $this->headStyle(); ?>
    
	<script type="text/javascript">
		var site			  = "<?php echo "http://" . $_SERVER["SERVER_NAME"]; ?>";
		var baseUrl           = "<?php echo $this->baseUrl(); ?>";
		var acoesUsuario      = Array(<?php echo $this->acoesUsuario(); ?>);
		var no_module         = "<?php echo $no_module; ?>";
		var no_controller     = "<?php echo $no_controller; ?>";
		var no_action         = "<?php echo $no_action; ?>";
        var cd_transacao      = "<?php echo $cd_transacao; ?>";
		var column  	      = "<?php echo $this->column; ?>";
		var orderby 	      = "<?php echo $this->orderby; ?>";
		var operacao 	      = "<?php echo $this->operacao; ?>";
		var paginaAtual       = "<?php echo $this->paginaAtual; ?>";
		var paginaAnterior    = "<?php echo $this->CriptAHref($this->paginaAnterior[0], $this->paginaAnterior[1], "", array(), 3); ?>";
        var jasperUrl 	      = "<?php echo $jasperUrl; ?>";
        var fl_tp_tran        = "<?php echo $fl_tipo_transacao; ?>";
        var fl_perm           = "<?php echo $fl_permissao; ?>";
		var baseUrlController = site + baseUrl + "/" + no_module + "/" + no_controller;
		<?php	
			// Lê os arquivos JavaScript
			//Zend_Loader::loadFile($documentRoot . $this->baseUrl() . "/public/js/jquery/jquery-1.4.2.min.js"); echo "\n";			
			Zend_Loader::loadFile($documentRoot . $this->baseUrl() . "/public/js/jquery/jquery-1.7.min.js"); echo "\n";			
			Zend_Loader::loadFile($documentRoot . $this->baseUrl() . "/public/js/jquery/jquery-ui/js/jquery-ui-1.8.4.custom.min.js"); echo "\n";
			Zend_Loader::loadFile($documentRoot . $this->baseUrl() . "/public/js/jquery/jquery-ui/development-bundle/ui/i18n/ui.datepicker-pt-BR.js"); echo "\n";
			Zend_Loader::loadFile($documentRoot . $this->baseUrl() . "/public/js/jquery/plugins/jquery.ui.datetime.src.js"); echo "\n";
			Zend_Loader::loadFile($documentRoot . $this->baseUrl() . "/public/js/jquery/plugins/jquery.loading.1.6.4.js"); echo "\n";
			Zend_Loader::loadFile($documentRoot . $this->baseUrl() . "/public/js/jquery/plugins/jquery.masked_input.js"); echo "\n";
			Zend_Loader::loadFile($documentRoot . $this->baseUrl() . "/public/js/jquery/plugins/jquery.price_format.js"); echo "\n";
			Zend_Loader::loadFile($documentRoot . $this->baseUrl() . "/public/js/jquery/plugins/jquery.masked_money.js"); echo "\n";
			Zend_Loader::loadFile($documentRoot . $this->baseUrl() . "/public/js/jquery/plugins/facebox/facebox.js"); echo "\n";
			Zend_Loader::loadFile($documentRoot . $this->baseUrl() . "/public/js/jquery/plugins/jquery.base64.min.js"); echo "\n";
			Zend_Loader::loadFile($documentRoot . $this->baseUrl() . "/public/js/jquery/plugins/jquery.shortcut.js"); echo "\n";
            Zend_Loader::loadFile($documentRoot . $this->baseUrl() . "/public/js/jquery/plugins/jquery.blockUI.js"); echo "\n";
			Zend_Loader::loadFile($documentRoot . $this->baseUrl() . "/public/js/form.js"); echo "\n";
			Zend_Loader::loadFile($documentRoot . $this->baseUrl() . "/public/js/tabela.js"); echo "\n";
			Zend_Loader::loadFile($documentRoot . $this->baseUrl() . "/public/js/mascara.js"); echo "\n";
			Zend_Loader::loadFile($documentRoot . $this->baseUrl() . "/public/js/data.js"); echo "\n";
			Zend_Loader::loadFile($documentRoot . $this->baseUrl() . "/public/js/valida.js"); echo "\n";
			Zend_Loader::loadFile($documentRoot . $this->baseUrl() . "/public/js/calcula.js"); echo "\n";
			Zend_Loader::loadFile($documentRoot . $this->baseUrl() . "/public/js/evento.js"); echo "\n";
			Zend_Loader::loadFile($documentRoot . $this->baseUrl() . "/public/js/base.js"); echo "\n";
			Zend_Loader::loadFile($documentRoot . $this->baseUrl() . "/public/js/jquery/plugins/jquery-tooltip/jquery.tooltip.js"); echo "\n";
			Zend_Loader::loadFile($documentRoot . $this->baseUrl() . "/public/js/{$no_module}/$no_controller.js"); echo "\n";
		?>
        
		// Carrega por último no documento 
		$(document).ready(function() {
			// Mostra a tela de carregamento que 
    		// protege de alterações no conteúdo da página
    		Base.mostraTelaProtecao();
		});
	</script>
    
    <?php echo $this->headScript(); ?>
</head>
<body id="pai" class="janela-flutuante">
    <div id="distancia"></div>

    <div id="container">

		<div id="content">
		<?php 
		    // Mostra o conteudo das views(action) dos controllers
		    echo $this->layout()->content;
		?>
		</div>
		
		<div class="clear"></div>
	</div>
	
	<!-- Guarda o usuário logado -->
	<input type="hidden" name="_cd_usuario_logado" id="_cd_usuario_logado" value="<?php echo $sessao->perfil->CD_USUARIO; ?>" /> 
	<input type="hidden" name="_tp_usuario" id="_tp_usuario" value="<?php echo $sessao->perfil->TP_USUARIO; ?>" />
</body>
</html>