<?php echo $this->doctype();
	// Captura os dados da requisição
	$no_module     = $this->no_module;
	$no_controller = $this->no_controller;
	$no_action     = $this->no_action;
	
	// Captura o local de origem do servidor onde estão os arquivos
	$documentRoot = substr($_SERVER["DOCUMENT_ROOT"], 0, -1);
?>
<html>
<head>
	<?php echo $this->headTitle()."\n";?>
	<?php echo $this->headMeta()."\n";?>

	<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl();?>/public/styles/base.css" />
	<style type="text/css">
		<?php	
			// Lê os arquivos CSS
			Zend_Loader::loadFile($documentRoot . $this->baseUrl() . "/public/js/jquery/jquery-ui/development-bundle/themes/marca/jquery.ui.core.css"); echo "\n";
			Zend_Loader::loadFile($documentRoot . $this->baseUrl() . "/public/js/jquery/jquery-ui/development-bundle/themes/marca/jquery.ui.resizable.css"); echo "\n";
			Zend_Loader::loadFile($documentRoot . $this->baseUrl() . "/public/js/jquery/jquery-ui/development-bundle/themes/marca/jquery.ui.selectable.css"); echo "\n";
			Zend_Loader::loadFile($documentRoot . $this->baseUrl() . "/public/js/jquery/jquery-ui/development-bundle/themes/marca/jquery.ui.accordion.css"); echo "\n";			
			Zend_Loader::loadFile($documentRoot . $this->baseUrl() . "/public/js/jquery/jquery-ui/development-bundle/themes/marca/jquery.ui.button.css"); echo "\n";
			Zend_Loader::loadFile($documentRoot . $this->baseUrl() . "/public/js/jquery/jquery-ui/development-bundle/themes/marca/jquery.ui.dialog.css"); echo "\n";
			Zend_Loader::loadFile($documentRoot . $this->baseUrl() . "/public/js/jquery/jquery-ui/development-bundle/themes/marca/jquery.ui.slider.css"); echo "\n";
            
		?>
	</style>	
	<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl();?>/public/styles/<?php echo $no_module;?>/<?php echo $no_controller;?>.css" />
	<?php 
	$documentRoot     = substr($_SERVER["DOCUMENT_ROOT"], 0, -1);
	$caminhoCssAction = "{$documentRoot}{$this->baseUrl()}/public/styles/{$no_module}/{$no_controller}-{$no_action}.css";
	// Verifica se o arquivo existe
	if(is_file($caminhoCssAction)) {
	?>
	<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl();?>/public/styles/<?php echo $no_module;?>/<?php echo $no_controller;?>-<?php echo $no_action;?>.css" />
	<?php
	} 
	?>
	<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl();?>/public/styles/imagens.css" />
	<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl();?>/public/js/jquery/jquery-ui/development-bundle/themes/marca/jquery.ui.all.css" />
	<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl();?>/public/js/jquery/plugins/ddsmoothmenu/ddsmoothmenu.css" />
	<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl();?>/public/js/jquery/plugins/jquery-tooltip/jquery.tooltip.css" />    
    
	
	<?php echo $this->headLink(); ?>
	<?php echo $this->headStyle(); ?>
    
	<script type="text/javascript">
		var site			  = "<?php echo "http://" . $_SERVER["SERVER_NAME"]; ?>";
		var baseUrl           = "<?php echo $this->baseUrl(); ?>";		
		var no_module         = "<?php echo $no_module; ?>";
		var no_controller     = "<?php echo $no_controller; ?>";
		var no_action         = "<?php echo $no_action; ?>";		
		var operacao 	      = "<?php echo $this->operacao; ?>";
		var paginaAnterior    = "<?php echo $this->CriptAHref($this->paginaAnterior[0], $this->paginaAnterior[1], "", array(), 3);?>";
		var baseUrlController = site + baseUrl + "/" + no_module + "/" + no_controller;				
		<?php	
			// Lê os arquivos JavaScript
			//Zend_Loader::loadFile($documentRoot . $this->baseUrl() . "/public/js/jquery/jquery-1.4.2.min.js"); echo "\n";			
			Zend_Loader::loadFile($documentRoot . $this->baseUrl() . "/public/js/jquery/jquery-1.7.min.js"); echo "\n";			
			Zend_Loader::loadFile($documentRoot . $this->baseUrl() . "/public/js/jquery/jquery-ui/js/jquery-ui-1.8.4.custom.min.js"); echo "\n";			
			Zend_Loader::loadFile($documentRoot . $this->baseUrl() . "/public/js/valida.js"); echo "\n";
			Zend_Loader::loadFile($documentRoot . $this->baseUrl() . "/public/js/base.js"); echo "\n";
            Zend_Loader::loadFile($documentRoot . $this->baseUrl() . "/public/js/jquery/plugins/jquery.base64.min.js"); echo "\n";
			Zend_Loader::loadFile($documentRoot . $this->baseUrl() . "/public/js/jquery/plugins/jquery-tooltip/jquery.tooltip.js"); echo "\n";
			Zend_Loader::loadFile($documentRoot . $this->baseUrl() . "/public/js/{$no_module}/$no_controller.js"); echo "\n";
		?>
	</script>
	
    <?php echo $this->headScript(); ?>
</head>
<body>
    <div id="distancia" style="height:45%;"></div>
    
    <div id="container" style="min-height:265px;">
		<?php
		    // Mostra mensagem na tela
		    if(isset($this->mensagemSistema)) {
		        echo $this->mensagemSistema;		        
		    }

		    // Mostra o conteudo das views(action) dos controllers
		    echo $this->layout()->content;
		?>
	</div>
</body>
</html>