<?php 

// Define o tнtulo
$titulo = "Relaзгo de Usuбrios";

// Converte o resultado para array
$resultado = $this->resConsulta->toArray();

// Formatando os campos
foreach($resultado as $indice => $valor) {
    
    // Formata o campo tipo de usuбrio
    $resultado[$indice]["TP_USUARIO"] = $valor["TP_USUARIO"] == "C" ? "Cliente" : "Do Porto"; 
    
    // Formata o campo super usuбrio
    $resultado[$indice]["FL_SUPER"] = $valor["FL_SUPER"] == "1" ? "Sim" : "Nгo";
    
    // Formata o campo acesso a intranet
    $resultado[$indice]["FL_ACESSO_INTRANET"] = $valor["FL_ACESSO_INTRANET"] == "1" ? "Sim" : "Nгo";
    
}

// Monta o array com os campos da consulta que serгo mostrados no relatуrio. -> (Obrigatуrio)
// Total 190 mm somando todos os campos para A4 tipo Retrato (P: Portrait)
// ou 277 mm somando todos os campos para A4 tipo Paisagem (L: Landscape)
$campos = array("NR_MATRIC"          => array("width"=>20, "text-align"=>'left',  "title"=>"Matrнcula"),
                "NO_USUARIO"         => array("width"=>87, "text-align"=>'left',  "title"=>"Nome"),
                "CD_USUARIO"         => array("width"=>30, "text-align"=>'left',  "title"=>"Usuбrio/Username"),
                "TP_USUARIO"         => array("width"=>15, "text-align"=>'left',  "title"=>"Tipo"),
                "FL_SUPER"           => array("width"=>23, "text-align"=>'left', "title"=>"Super Usuбrio"),
                "FL_ACESSO_INTRANET" => array("width"=>15, "text-align"=>'left', "title"=>"Intranet"));

// Chama o view helper que gerarб o relatуrio
$this->geraRelatorio($resultado, $titulo, $campos, $this->extraParams["_rel_metodo"]);
?>