<?php
// Seta o título
$this->headTitle("Tabelas - Pesquisa");
?>

<form name="f1">
	<input type="hidden" value="<?php echo $this->controleSalvar; ?>" name="controleSalvar" id="controleSalvar" />
    <?php
    // Seta as ligações entre as tabelas
    echo "<select id='coluna_tabelas_origem' style='display: none;'>";
    echo "<option value='_null_' label='-- Selecione --' sigla=''>-- Selecione --</option>";
    foreach($this->colTabelas as $colunaTabela) {
        $valor = trim($colunaTabela->SG_TABELA) . "." . $colunaTabela->CD_COLUNA;
        $label = trim($colunaTabela->SG_TABELA) . "." . $colunaTabela->NO_COLUNA;
        $sigla = trim($colunaTabela->SG_TABELA);
        echo "<option value='{$valor}' sigla='{$sigla}' coluna='{$colunaTabela->CD_COLUNA}' tp_coluna='{$colunaTabela->TP_COLUNA}' nome='{$colunaTabela->NO_COLUNA}' label='{$label}'>{$label}</option>";
    }
    echo "</select>";
    
    // Seta os filtros das colunas das tabelas
    echo "<select id='filtros_origem' style='display: none;'>";
    foreach($this->filtros as $filtro) {
        echo "<option value='{$filtro->CD_TP_FILTRO}' label='{$filtro->DS_TP_FILTRO}'>{$filtro->DS_TP_FILTRO}</option>";
    }
    echo "</select>";
    ?>
</form>

<form id="form_base" method="post" accept-charset="ISO-8859-1" onsubmit="return false;" action="">
    <input type="hidden" value="<?php echo $this->pai_cd_consulta; ?>" name="pai_cd_consulta" id="pai_cd_consulta" />
    <table class='tabela nao-ordenavel nao-selecionavel' id='tabelaConsulta'>
        <thead>
            <tr>
                <th class='abre_par'> ( </th>
                <th class='coluna'>Coluna</th>
                <th class='tp_ligacao'>Ligação</th>
                <th class='ds_complemento'>Complemento</th>
                <th class='lig_int_par'> e/ou </th>
                <th class='fecha_par'> ) </th>
                <th class='lig_ext_par'> e/ou </th>
                <th class='add'><img class='add_cond_col' alt='Nova Condição' src='<?php echo $this->baseUrl(); ?>/public/images/botoes/16x16_adicionar.png' class='del_linha' /></th>
            </tr>
        </thead>
        <tbody>
        </tbody>
    </table>
</form>