<?php
// Seta o título
$this->headTitle("Relatório de Eventos - Pesquisa");
?>

<!-- Formulario de cadastro -->
<form id="form_pesquisar" method="post" accept-charset="ISO-8859-1" accept-submit="false" onsubmit="return false;" action="">
    <fieldset>
        <legend>Pesquisa</legend>

        <div class="linha">
            <div class="left">
                <label class="label_esquerda" for="dthr_acesso_ini">Período:</label>
                <?php echo $this->formText("dthr_acesso_ini", $this->form['dthr_acesso'], array('class'=>'data', 'maxlength'=>'10'));?>
                <?php echo $this->formText("dthr_acesso_fim", $this->form['dthr_acesso'], array('class'=>'data', 'maxlength'=>'10'));?>
            </div>
        </div>

        <div class="linha">
            <div class="left">
                <label class="label_esquerda" for="usuario">Usuário:</label>
                <?php echo $this->formText("usuario", $this->form['usuario'], array('class'=>'auto-complete-x', 'maxlength'=>'50'));?>
                <?php echo $this->formHidden("cd_usuario", $this->form['cd_usuario'], array());?>
            </div>
        </div>
        
    </fieldset>
    
</form>
